In [2]:
import h5py
import numpy as np

In [4]:
neki = np.arange(1, 11, 1).reshape(5,2)

In [28]:
with h5py.File('test', 'w') as f:
    
    f.create_dataset('neki', data=neki, maxshape=(5,None))

In [35]:
with h5py.File('test', 'a') as f:
    
    keylist = f.keys()
    print(keylist)
    
    neki1 = np.arange(1,21,1).reshape(5,4)
    
    #f['neki'][()] = neki1
    print(f['neki'][()])
    f['neki'].resize((5))

    f['neki'][:2, :] = neki1[:2,:]
    print(f['neki'][()])
    print(f['neki'].shape)

<KeysViewHDF5 ['neki']>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]]


TypeError: 'int' object is not iterable

In [31]:
slovar = {'neki':1, 'neki1':2}

for key, value in slovar.items():
    print(key, value)

neki 1
neki1 2


In [32]:
neki = np.arange(1,11,1).reshape(5,2)

In [45]:
neki[np.ix_([1:])]

SyntaxError: invalid syntax (<ipython-input-45-5611839c13eb>, line 1)

In [46]:
np.ix_([1:])

SyntaxError: invalid syntax (<ipython-input-46-367b742f2bdb>, line 1)

In [47]:
slovar.values()

dict_values([1, 2])

In [51]:
neki[np.array([1,3]),:]

array([[3, 4],
       [7, 8]])